# Dark powerded Vim/Neovim plugin manager
[[plugins]]
repo = 'shougo/dein.vim'

# Lean & mean status/tabline for vim
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# Visualizing indentation
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_char = '¦'
  let g:indentLine_leadingSpaceChar = '·'
  let g:indentLine_leadingSpaceEnabled = 1
'''
# auto pair completion
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# Language Server Protocol
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0
hook_add = '''
  source ~/.config/nvim/rc/plugins/coc.nvim.rc.vim
'''

# Syntax for TOML
[[plugins]]
repo = 'cespare/vim-toml'

# Syntax highlighting, matching rules aand mappings for markdown
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

# This plug-in is disabled for coc.nvim
# # Lint tool
# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = '''
# let g:ale_sign_column_always = 1
# let g:ale_fix_on_save = 1
# let g:ale_lint_on_text_changed = 0
# let g:ale_linters = {
#   \'rust': ['cargo', 'rls']
# \}
# nmap <silent> <C-w>k <Plug>(ale_previous_wrap)
# nmap <silent> <C-w>j <Plug>(ale_next_wrap)
# '''

